services:
  postgres:
    image: docker.io/bitnami/postgresql:latest
    ports:
      - "5434:5432"
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=todoapp


