//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type TodoItems struct {
	ID        int32 `sql:"primary_key"`
	Title     string
	Status    *int32
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    int32
}

type TodoItemsInsert struct {
	Title     string
	UserID    int32
}

type TodoItemsUpdate struct {
	ID        int32 `sql:"primary_key"`
	Title     string
	Status    *int32
	UpdatedAt time.Time
	UserID    int32
}
